### ISSUE TITLE
Proposal: Collapsing the 3 stores

### ISSUE THREAD

**Issue by gamarin2** [cosmos/sdk-application-tutorial#1]
Currently there are three stores for the nameservice module. I think we should collapse them into one. This would have the following benefits:

- Mirror current best practices in existing modules
- Add a `types.go` file to the module for the struct that would contain `{value, price, owner}`, which would help readers understand its use. They will likely have to have one if they ever build their own module. 
- Unmarshalling overhead is ok since we always use at least 2/3 fields of the struct in functions.

**Comment by jackzampolin** [comment]
While I do see value in showing how to use encoding with the storage layer, I think it's much better for user understanding if we have the stores separated. This would also make some of the getters/setters more complicated. Don't think there are pros or cons large enough to justify reworking the tutorial however.

**Comment by gamarin2** [comment]
> I think it's much better for user understanding if we have the stores separated

Why? I don't necessarily agree. The first question I asked was "why do I need one store for each field if the key is the same?". 

The follow up question would be "Does that mean that if I have 15 fields I should have 15 stores?". 
And because the answer is obviously no, then I think we need to introduce types.go and amino encoding of structs. 

> This would also make some of the getters/setters more complicated

Barely.

Overall this is not that big of a change, does not add much complexity and I think it showcases important concepts that users should be aware of.

**Comment by jackzampolin** [comment]
You have convinced me here. Lets go ahead and make this change

**Comment by sunnya97** [comment]
@gamarin2 @jackzampolin 
Should I do this before my EthCC workshop?

**Comment by marbar3778** [comment]
These changes are already in the tutorial. Will close the issue.
