### ISSUE TITLE
Typo(s) in SDK tutorial

### ISSUE THREAD

**Issue by austinabell** [cosmos/sdk-application-tutorial#101]
In the [step of creating types for the module](https://github.com/cosmos/sdk-application-tutorial/blob/master/tutorial/types.md) it is referenced that the file should be created at `./x/nameservice/types.go` but the package is types for the code so it should be noted it is created at `./x/nameservice/types/types.go`.

I am assuming this is a typo because [in the following step](https://github.com/cosmos/sdk-application-tutorial/blob/master/tutorial/key.md) it says "Start by creating a key.go file withing in the types folder" (withing also a typo) and in the [example code](https://github.com/cosmos/sdk-application-tutorial/tree/master/x/nameservice/types) the files are in that folder.

**Comment by austinabell** [comment]
Also in [setting up the keeper](https://github.com/cosmos/sdk-application-tutorial/blob/master/tutorial/keeper.md) there is a line in the code block that redefines the StoreKey. 

```go
// StoreKey to be used when creating the KVStore
const StoreKey = "ns"
```

I assume this is old, since the tutorial code references the one created in [../types/key.go](https://github.com/cosmos/sdk-application-tutorial/blob/master/x/nameservice/types/key.go).

**Comment by austinabell** [comment]
In [AppModule declaration](https://github.com/cosmos/sdk-application-tutorial/blob/master/tutorial/module.md) `RegisterRESTRoutes` function is:

```go
// Register rest routes
func (AppModuleBasic) RegisterRESTRoutes(ctx context.CLIContext, rtr *mux.Router, cdc *codec.Codec) {
	rest.RegisterRoutes(ctx, rtr, cdc, StoreKey)
}
```

and has removed the codec parameter the function signature has since been updated to:

```go
// Register rest routes
func (AppModuleBasic) RegisterRESTRoutes(ctx context.CLIContext, rtr *mux.Router) {
	rest.RegisterRoutes(ctx, rtr, StoreKey)
}
```

**Comment by austinabell** [comment]
Last and final change to get the tutorial to build (aside from hacky go modules workarounds) was to add this code block in `app.go` taken from the example code:

```go
// GenesisState represents chain state at the start of the chain. Any initial state (account balances) are stored here.
type GenesisState map[string]json.RawMessage

func NewDefaultGenesisState() GenesisState {
	return ModuleBasics.DefaultGenesis()
}

func (app *nameServiceApp) InitChainer(ctx sdk.Context, req abci.RequestInitChain) abci.ResponseInitChain {
	var genesisState GenesisState

	err := app.cdc.UnmarshalJSON(req.AppStateBytes, &genesisState)
	if err != nil {
		panic(err)
	}

	return app.mm.InitGenesis(ctx, genesisState)
}

func (app *nameServiceApp) BeginBlocker(ctx sdk.Context, req abci.RequestBeginBlock) abci.ResponseBeginBlock {
	return app.mm.BeginBlock(ctx, req)
}
func (app *nameServiceApp) EndBlocker(ctx sdk.Context, req abci.RequestEndBlock) abci.ResponseEndBlock {
	return app.mm.EndBlock(ctx, req)
}
func (app *nameServiceApp) LoadHeight(height int64) error {
	return app.LoadVersion(height, app.keyMain)
}

//_________________________________________________________

func (app *nameServiceApp) ExportAppStateAndValidators(forZeroHeight bool, jailWhiteList []string,
) (appState json.RawMessage, validators []tmtypes.GenesisValidator, err error) {

	// as if they could withdraw from the start of the next block
	ctx := app.NewContext(true, abci.Header{Height: app.LastBlockHeight()})

	genState := app.mm.ExportGenesis(ctx)
	appState, err = codec.MarshalJSONIndent(app.cdc, genState)
	if err != nil {
		return nil, nil, err
	}

	validators = staking.WriteValidators(ctx, app.stakingKeeper)

	return appState, validators, nil
}
```
sorry if being verbose and could have just been more concise in saying update code blocks in these past couple comments

**Comment by marbar3778** [comment]
Thank you for the issue. Yes, you are correct that the code was updated but not all the docs of the tutorial were. I  apologize for that. 

What was the issue that you were running into with go.mod that you had to do a hacky workaround?

**Comment by austinabell** [comment]
> The last comment you made the code was in the tutorial and the code, what was the error you ran into that you had to add it.
> 
> https://github.com/cosmos/sdk-application-tutorial/blob/master/app.go#L255
> https://github.com/cosmos/sdk-application-tutorial/blob/master/app.go#L284

You're right! My apologies, I must have searched for the wrong thing or missed it.

Issue with go.mod was that it didn't work out of the box without the modules downloaded to the cache. I can't remember exactly what the issue was other than one was:
```
cannot load github.com/cosmos/cosmos-sdk/x/auth/client/utils: cannot find module providing package github.com/cosmos/cosmos-sdk/x/auth/client/utils
```

And unfortunately I wasn't patient enough to actually debug so I ended up just copying the go.mod and go.sum from the example code to download the correct versions to the module cache.

**Comment by marbar3778** [comment]
hmm, and now when you try are you running into the same issue?

**Comment by austinabell** [comment]
Hey thanks for getting to this! I missed this comment yesterday but saw the PR #104. I was not having issues on my end, I got it to work, I just put in the issue to help with the tutorial md files to match the updated code structures.

One small thing I noticed with the changes is that the build will fail because the `RegisterRESTRoutes` function has the wrong function signature. I see that in the md and code example they call the function without the codec, so I think the function signature might be:

```go
// Register rest routes
func (AppModuleBasic) RegisterRESTRoutes(ctx context.CLIContext, rtr *mux.Router) {
	rest.RegisterRoutes(ctx, rtr, StoreKey)
}
```

with `, cdc *codec.Codec` taken from the function signature from:

```go
func (AppModuleBasic) RegisterRESTRoutes(ctx context.CLIContext, rtr *mux.Router, cdc *codec.Codec) {
```
and not just take the codec out of the `rest.RegisterRoutes(..)` call.

Thanks again for addressing this quickly and I hope this helps!

**Comment by marbar3778** [comment]
That is odd, it builds normally and I am able to use the given routes without any issue, can you post the error that is outputted on the build

**Comment by austinabell** [comment]
oh sorry I wasn't specific, I'm just referring to the md file, not the example code. In the [markdown](https://github.com/cosmos/sdk-application-tutorial/blob/c0e89a01fe21821d67adf470b56d0114d0b7890d/tutorial/module.md) The function is

```
func (AppModuleBasic) RegisterRESTRoutes(ctx context.CLIContext, rtr *mux.Router, cdc *codec.Codec) {
	rest.RegisterRoutes(ctx, rtr, StoreKey)
}
```

where in [the example code](https://github.com/cosmos/sdk-application-tutorial/blob/c0e89a01fe21821d67adf470b56d0114d0b7890d/x/nameservice/module.go#L53), The function signature has the codec removed.

Sorry if it would have been easier for me to just open a PR with the changes, I just wasn't sure with you guys updating the code structure if those changes were final or not.

**Comment by marbar3778** [comment]
Ah thank you @austinabell, I made a PR #106  on it.
