### ISSUE TITLE
No go.mod document in web tutorial, and outdated dependencies in github tutorial

### ISSUE THREAD

**Issue by psy2848048** [cosmos/sdk-application-tutorial#105]
Hi,

Currently I'm developing under sdk-tutorial's guide and there is no dependency setting doc in web tutorial.
https://cosmos.network/docs/tutorial/gomod.html

And it seems to be outdated in github tutorial.
If you don't provide go.mod and install by only `go get`, the CLI&daemon build fails like https://github.com/cosmos/cosmos-sdk/issues/4179
Please update the doc the latest version :)

Many thanks,
Bryan

**Comment by psy2848048** [comment]
Given direct link works but the link in this document doesn't work.
https://cosmos.network/docs/tutorial/entrypoint.html#nscli

**Comment by marbar3778** [comment]
yes, we had to do this for a specific reason, once there is a new release of the sdk this will be updated to display the correct information. We are working on a better solution which will be released soon, thank you the opening of the issue
