### ISSUE TITLE
how to add nodes to nameservice p2p network?

### ISSUE THREAD

**Issue by lilianwen** [cosmos/sdk-application-tutorial#107]
when i edit the config file of another node as below:
seeds = "7e7f945ec5cae856a1e9bd287ef0fd9da6ac0431@10.168.15.121:26656"

I start the new node,but errors show:
I[2019-06-28|15:49:16.935] Starting ABCI with Tendermint                module=main 
E[2019-06-28|15:49:16.984] Error signing vote                           module=consensus height=1 round=0 vote="Vote{0:E4496DC3C236 1/00/1(Prevote) 000000000000 000000000000 @ 2019-06-28T07:49:16.984694763Z}" err="error signing vote: height regression. Got 1, last height 710"
E[2019-06-28|15:49:16.986] Error dialing seed                           module=p2p err="dial tcp 10.168.15.121:26656: connect: no route to host" seed=7e7f945ec5cae856a1e9bd287ef0fd9da6ac0431@10.168.15.121:26656
E[2019-06-28|15:49:16.986] Couldn't connect to any seeds                module=p2p 

how to solve this problem?

**Comment by marbar3778** [comment]
Are you using the same genesis? also are you running on the same computer or separate?

**Comment by lilianwen** [comment]
> Are you using the same genesis? also are you running on the same computer or separate?

it is my fault, i did not close my firewall.

**Comment by hussein1571** [comment]
hello @marbar3778 , 
 
I[2019-08-09|14:41:33.100] Executed block  module=state height=16400 validTxs=0 invalidTxs=0
I[2019-08-09|14:41:33.145] Committed state  module=state height=16400 txs=0 appHash=785E82D6DC464600CC567D1FDEE11A33F752E05E7332F9FA1CF466186D4CB1D7
I[2019-08-09|14:41:38.398] Executed block  module=state height=16401 validTxs=0 invalidTxs=0
I[2019-08-09|14:41:38.444] Committed state module=state height=16401 txs=0 appHash=41EAC7064DA0A35077C472ACF5E3CC2F0622DEC1753D955AFAF2DEFB04114639
**E[2019-08-09|14:41:40.859] Connection failed @ recvRoutine (reading byte) module=p2p peer=65f742dc5a6fc8c4d4ba51e390ab011f3b8bce1b@192.168.43.6:39514 conn=MConn{192.168.43.6:39514} err=EOF**
E[2019-08-09|14:41:40.860] Stopping peer for error  module=p2p peer="Peer{MConn{192.168.43.6:39514} 65f742dc5a6fc8c4d4ba51e390ab011f3b8bce1b in}" err=EOF
I[2019-08-09|14:41:43.737] Executed block module=state height=16402 validTxs=0 invalidTxs=0
I[2019-08-09|14:41:43.781] Committed statemodule=state height=16402 txs=0 appHash=7483BCE4020A381D3FA2E0E8F9971CFB93321EBA5ECA05FC2721D0CCA691B2DD




**I use the same genesis, but seperated pc** ,  I can't connect the two nodes (connection faild @ recvRoutine) could you help me ?

**Comment by luandt** [comment]
I had the same issue. I installed a node in AWS EC2 with the open port 26656 in the security group. I've been running a local node in my computer and connect to the one on AWS.
This is error:
**Error dialing peer                           module=p2p err="dial tcp 54.255.192.232:26656: connect: no route to host"**

Does Anyone know how to solve this issue?
Thanks

**Comment by marbar3778** [comment]
please make sure you are using your public IP, when I use ec2 my public IP usually starts with ec2

**Comment by luandt** [comment]
I'm using the public IP and there is also a public DNS starts with ec2. I've replaced with DNS one but it seems EC2 instance did not work on port 26656 even though it's opening and added to security group.

**Comment by luandt** [comment]
There is a another firewall running which I was not aware of. Just turn off and it has backed to normal
