### ISSUE TITLE
Can we please make sure the tutorial is backward compatible or at least stay up to date

### ISSUE THREAD

**Issue by amazingandyyy** [cosmos/sdk-application-tutorial#113]
Can we please make sure the tutorial is backward compatible or at least stay up to date.

### THIS IS A HUGE BLOCKER FOR PEOPLE TO JOIN THE COSMOS ECOSYSTEM.

Or can we include a verification  process that tutorial itself work with the lates ask codebase!?

**Comment by marbar3778** [comment]
The codebase was updated last week to the master branch , I was waiting for 0.36 of the cosmos-SDK to be released to do the next update of the tutorial. this will be in the following week.

**Comment by amazingandyyy** [comment]
Thank you @marbar3778 for the great efforts.
