### ISSUE TITLE
Doubt in makefile

### ISSUE THREAD

**Issue by enakshipriya** [cosmos/sdk-application-tutorial#114]
Hi,

I was going through the master branch of sdk-application-tutorial
https://github.com/cosmos/sdk-application-tutorial/blob/master/go.mod

Here the cosmos-sdk version mentioned is v0.28.2-0.20190616100639-18415eedaf25 which is probably a deprecated version. Sometimes go.mod automatically updates it to v0.35.0.

Anyways the main issue here is that none of these version contains the following packages(or atleast either of the packages):
**github.com/cosmos/cosmos-sdk/types/module**
**github.com/cosmos/cosmos-sdk/x/auth/genaccounts**

These packages are being imported in app.go. You can find it here:
https://github.com/cosmos/sdk-application-tutorial/blob/master/app.go

I am really confused how the makefile is working in such a scenario when the modules doesn't exist because when i try to do the same thing in my application its throwing error as follows:

cannot load github.com/cosmos/cosmos-sdk/types/module: import lookup disabled by -mod=readonly
Makefile:5: recipe for target 'install' failed
make: *** [install] Error 1

Makefile used by me is same as one here:
https://github.com/cosmos/sdk-application-tutorial/blob/master/Makefile

Please let me know what other changes i should make for the makefile to work. The error that i am getting is expected according to me but its surprising how the same error is not thrown in case of nameservice app. Please let me know of the hack.

I am facing similar errors when i am trying to make changes in gaiacli. Its makefile stops creating binaries on making any change and keeps throwing error until you revert it back to original.
--

**Comment by marbar3778** [comment]
That version is the master branch of the cosmos-sdk repo of which was used for the sdk-tutorial when it was updated. v0.35.0 does not have `/genaccounts` and `types/module`. 

from the make file this line: 
`go install -mod=readonly $(BUILD_FLAGS) ./cmd/nsd`

just means that it will not overwrite the go.mod file. 

when you changed your version did you run go get github.com/cosmos/cosmos-sdk@<commit_hash> or just put it in? I will also be updating the tutorial with the most recent version 0.36.0 when it's released in the coming days.

**Comment by enakshipriya** [comment]
Hey, I did that actually. The master branch till this commit 67f6b021180c7ef0bcf25b6597a629aca27766b8 is there in my GOPATH at location go/src/github.com/cosmos/cosmos-sdk. Its still importing from the following location: /home/cosmos/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.35.0/ and throwing the same error.

**Comment by marbar3778** [comment]
`genaccounts` is no longer in auth but its own module, so import would be `x/genaccounts` instead. Also there isn't a need for you to have the specific version locally, go.mod is being used here so that previous go process has been replaced.

**Comment by enakshipriya** [comment]
Hey **@marbar3778** , i did what you said. The above errors are gone but i am getting new errors as follow:

```
# github.com/cosmos/cosmos-sdk/types
../go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.28.2-0.20190616100639-18415eedaf25/types/result.go:102:43: res.TxResult.Tags undefined (type "github.com/tendermint/tendermint/abci/types".ResponseDeliverTx has no field or method Tags)
../go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.28.2-0.20190616100639-18415eedaf25/types/result.go:144:42: res.CheckTx.Tags undefined (type "github.com/tendermint/tendermint/abci/types".ResponseCheckTx has no field or method Tags)
../go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.28.2-0.20190616100639-18415eedaf25/types/result.go:171:44: res.DeliverTx.Tags undefined (type "github.com/tendermint/tendermint/abci/types".ResponseDeliverTx has no field or method Tags)
make: *** [install] Error 2
```

**Comment by marbar3778** [comment]
I'm not sure if you resolved the issue, but in this PR, I am updating the tutorial and it builds correctly, need to double check a few things and update the docs and it will be merged

**Comment by brentmcd** [comment]
@marbar3778 Following your instructions above, we're also seeing issues with `x/genaccounts` for `0.35.0`:

```
go: finding github.com/cosmos/cosmos-sdk/x/genutil latest
go: finding github.com/cosmos/cosmos-sdk/x/genaccounts latest
go: finding github.com/cosmos/cosmos-sdk/x latest
build [HIDDEN]: cannot load github.com/cosmos/cosmos-sdk/x/genaccounts: cannot find module providing package github.com/cosmos/cosmos-sdk/x/genaccounts

**Comment by marbar3778** [comment]
in `0.35.0` I don't believe genaccounts and genutil exist, they are in the `0.36.0` release, this is why i believe you have the problem. this is the PR, you can have a look at some of the changes: https://github.com/cosmos/sdk-application-tutorial/pull/120

**Comment by marbar3778** [comment]
the PR has been merged, this error should be present anymore, closing the issue, if you run into issues, please comment here and I'll respond as soon as I can, thank you

**Comment by jacohend** [comment]
Getting this error with a fresh go workspace, on master:
```
build github.com/cosmos/sdk-application-tutorial/cmd/nsd: cannot load github.com/cosmos/cosmos-sdk/types/module: cannot find module providing package github.com/cosmos/cosmos-sdk/types/module
```
Seems to be the same issue. Any suggestions?

**Comment by AlexMesser** [comment]
https://github.com/tendermint/tendermint/tree/master/libs also no longer contains `db` module

**Comment by jacohend** [comment]
@marbar3778 Can these issues be fixed, or do you know steps to address them?

**Comment by marbar3778** [comment]
Hey, sorry for the delat, if you pull master this should not be the case anymore. If it still is, please post your go.mod file. 

The reason I am guessing is that you are using older code but newer versions of cosmos & tendermint
