### ISSUE TITLE
The file 'sdk-application-tutorial/tutorial/cn/15-build-run.md' is wrong!

### ISSUE THREAD

**Issue by jerryma0912** [cosmos/sdk-application-tutorial#116]
File Path:  sdk-application-tutorial/tutorial/cn/15-build-run.md

ERROR Sentence:  rm -rf~ / .ns * 
(如果你之前已经运行过该教程，则可以从头开始使用nsd unsafe-reset-all或删除home文件夹下的两个执行程序的数据及配置文件夹rm -rf~ / .ns *)

Correct Sentence:  rm -rf ~/.ns*

Consequence: ALL file in $Home folder have been DELETED !!!!!! BAD STORT!! Please must modify this error immediately! Thanks!

**Comment by marbar3778** [comment]
Sorry for the inconvenience, It has been fixed.  👍
