### ISSUE TITLE
Build Issue

### ISSUE THREAD

**Issue by thomasbeukema** [cosmos/sdk-application-tutorial#119]
Hi, I am trying to make this tutorial work. I followed along with it, but when I try to run 'make install' it give me this error: 
`GO111MODULE=on go mod verify
all modules verified
go install -mod=readonly  ./cmd/nsd
build flag -mod=readonly only valid when using modules
Makefile:6: recipe for target 'install' failed
make: *** [install] Error 1`

and when I try to run 'go build nsd.go' or 'go build nscli.go', I get this error:
`# github.com/tendermint/tendermint/crypto/ed25519
/media/thomas/Storage/Documents/Programming/go/src/github.com/tendermint/tendermint/crypto/ed25519/ed25519.go:108:13: undefined: ed25519.NewKeyFromSeed
/media/thomas/Storage/Documents/Programming/go/src/github.com/tendermint/tendermint/crypto/ed25519/ed25519.go:121:13: undefined: ed25519.NewKeyFromSeed
 github.com/tendermint/iavl
/media/thomas/Storage/Documents/Programming/go/src/github.com/tendermint/iavl/node.go:112:3: undefined: common.ColoredBytes
/media/thomas/Storage/Documents/Programming/go/src/github.com/tendermint/iavl/node.go:112:30: undefined: common.Green
/media/thomas/Storage/Documents/Programming/go/src/github.com/tendermint/iavl/node.go:112:41: undefined: common.Blue
/media/thomas/Storage/Documents/Programming/go/src/github.com/tendermint/iavl/node.go:113:3: undefined: common.ColoredBytes
/media/thomas/Storage/Documents/Programming/go/src/github.com/tendermint/iavl/node.go:113:32: undefined: common.Cyan
/media/thomas/Storage/Documents/Programming/go/src/github.com/tendermint/iavl/node.go:113:42: undefined: common.Blue`

Does anyone know how to resolve these? Thanks!

**Comment by marbar3778** [comment]
Can you please post which version of tendermint and iavl you have in your go.mod file?

**Comment by thomasbeukema** [comment]
This is what my go.mod file looks like.

'module github.com/thomasbeukema/nameservice

go 1.12

require (
	github.com/cosmos/cosmos-sdk v0.28.2-0.20190616100639-18415eedaf25
	github.com/gorilla/mux v1.7.0
	github.com/mattn/go-isatty v0.0.7 // indirect
	github.com/prometheus/procfs v0.0.0-20190328153300-af7bedc223fb // indirect
	github.com/spf13/afero v1.2.2 // indirect
	github.com/spf13/cobra v0.0.3
	github.com/spf13/pflag v1.0.3
	github.com/spf13/viper v1.0.3
	github.com/syndtr/goleveldb v1.0.0 // indirect
	github.com/tendermint/go-amino v0.15.0
	github.com/tendermint/tendermint v0.31.5
	golang.org/x/sys v0.0.0-20190329044733-9eb1bfa1ce65 // indirect
	google.golang.org/genproto v0.0.0-20190327125643-d831d65fe17d // indirect
	google.golang.org/grpc v1.19.1 // indirect
)'
