### ISSUE TITLE
Context refactoring issue

### ISSUE THREAD

**Issue by xr9kayu** [cosmos/sdk-application-tutorial#123]
Can you upgrade tutorial for tx cmd queries?  GetCmdSetName and GetCmdBuyName use functions that dont exist after refactoring.

**Comment by marbar3778** [comment]
yes, working on it here, will update docs today and then be ready to merge

**Comment by marbar3778** [comment]
The pr has been merged, will close this issue, if you run into the same issue, feel free to comment here and I'll anser as soon as i can
