### ISSUE TITLE
Transaction signing

### ISSUE THREAD

**Issue by xr9kayu** [cosmos/sdk-application-tutorial#124]
What libs and functions in the cosmos-sdk i can use to sign transaction on the frontend (user-appcilation)? Explain please how can i do this on the example of the nameservice (tutor. app)?

Sorry for mis subject, but i cant find answer anywhere :\

**Comment by marbar3778** [comment]
Lunie provides a few good libraries to use within the JS world. 

https://github.com/luniehq/cosmos-api
https://github.com/luniehq/cosmos-keys

**Comment by marbar3778** [comment]
Will close this issue, were you able to find the answer you were looking for?
