### ISSUE TITLE
why is height of the query always 0?

### ISSUE THREAD

**Issue by hquzs** [cosmos/sdk-application-tutorial#125]
As the title shows. When I tested running the tutorial,the height of transaction is always 0..

**Comment by hquzs** [comment]
As the title shows. When I tested running the tutorial,the height of blockchain is always 0..

run:
nscli tx nameservice buy-name jack.11 5nametoken --from jack
get:
......
confirm transaction before signing and broadcasting [y/N]: y
Password to sign with 'jack':
{
  "height": "0",
  "txhash": "BA252AF11915E58B947AE832A602240D7FB7054A5346714DEAFD5A0F5AA52AE9"
}

**Comment by jackzampolin** [comment]
This is an issue we are currently fixing in the SDK.
