### ISSUE TITLE
Adding a root url

### ISSUE THREAD

**Issue by adityanalge** [cosmos/sdk-application-tutorial#20]
When the nsd blockchain is running, I can go to http://localhost:26657/ to see all the available endpoints.

Is it possible to create a similar user experience when it comes to nscli rest server? providing the user with json-rpc endpoints that can be used to GET account balances, resolve names or send transactions?

If such a feature already exists, could someone point me to it?

**Comment by jackzampolin** [comment]
@adityanalge In `gaia` we have a [swagger file](https://github.com/cosmos/cosmos-sdk/blob/develop/client/lcd/swagger-ui/swagger.yaml) that describes all the routes there and we have an open issue for adding more [modular support for this feature](https://github.com/cosmos/cosmos-sdk/issues/3011) in the SDK, but that would be a good deal of work. 

I don't see us adding this feature any time soon. Thank you for the suggestion tho!
