### ISSUE TITLE
Test nameservice create transection with Multithreading Error!!!!

### ISSUE THREAD

**Issue by SorawitSiri** [cosmos/sdk-application-tutorial#26]
Test nameservice create transection with Multithreading which result error and query not found the domain name  

**How to solve problem?**

<img width="1368" alt="screen shot 2562-01-18 at 19 23 51" src="https://user-images.githubusercontent.com/34050939/51390412-d0c72300-1b61-11e9-80de-0cebe2e8a3b1.png">

**Comment by jackzampolin** [comment]
Hello @sorawitsiri! I'm unsure what the issue is. I don't see anything having to do with multithreading in this issue.

**Comment by SorawitSiri** [comment]
@jackzampolin You can suggest me for test performance of transfer token about throughput(TPS). How to should test for performance of Cosmos SDK?

**Comment by jackzampolin** [comment]
I don't think this repo is the right spot to do that. Might want to check out the `cosmos-sdk` repo and test `gaiad`. We don't have any tooling for performing that kind of testing that is current, so you will need to use your own transaction generation.

**Comment by SorawitSiri** [comment]
Hello @jackzampolin  I'm unsure Nameservice, Do you can buy two nameservice parallel from cosmos/sdk-application-tutorial ?

**Comment by yangyanqing** [comment]
I got the following output after running the bash shell with master(2019-02-15), and the result was always one success and one fault. 

It seems like cli locked some resource while waiting nsd pack the tx, so another cli shell fail.

```json
ERROR: resource temporarily unavailable
{
 "height": "171",
 "txhash": "2855BC60070ECE0784A7D95648B0F85463878DE5F31C68337B954F802E226B27",
 "log": "Msg 0: ",
 "gas_wanted": "200000",
 "gas_used": "23759",
 "tags": [
  {
   "key": "action",
   "value": "buy_name"
  }
 ]
}
```

**Comment by yangyanqing** [comment]
master (2019-02-15)

Another output (`failed to get from fields: resource temporarily unavailable`) was found by using account name instead of address. This message only exist in `/cosmos/cosmos-sdk/client/context/context.go` . So I still consider the fail reason is lock of some cli resource.

```go
func NewCLIContext() CLIContext {
	var rpc rpcclient.Client

	nodeURI := viper.GetString(client.FlagNode)
	if nodeURI != "" {
		rpc = rpcclient.NewHTTP(nodeURI, "/websocket")
	}

	from := viper.GetString(client.FlagFrom)
	fromAddress, fromName, err := GetFromFields(from)
	if err != nil {
		fmt.Printf("failed to get from fields: %v", err)
		os.Exit(1)
	}
...
```
Details was as following.

```bash

➜  sdk-application-tutorial git:(master) ✗ echo "11111111" | nscli tx nameservice buy-name alice.id 10mycoin  --from alice
{
 "height": "789",
 "txhash": "B3AEE6F4BC78D34BB727880BBF8F1D002FD2057C31793ED2FBF2436A41B025CB",
 "log": "Msg 0: ",
 "gas_wanted": "200000",
 "gas_used": "23916",
 "tags": [
  {
   "key": "action",
   "value": "buy_name"
  }
 ]
}
➜  sdk-application-tutorial git:(master) ✗ echo "11111111" | nscli tx nameservice buy-name jack.id 10mycoin  --from jack 
{
 "height": "792",
 "txhash": "F060FF52252AEC97E5A74D82571657F7211196A6F28D7F8216A8EA7744409688",
 "log": "Msg 0: ",
 "gas_wanted": "200000",
 "gas_used": "23699",
 "tags": [
  {
   "key": "action",
   "value": "buy_name"
  }
 ]
}
➜  sdk-application-tutorial git:(master) ✗ ./batch-tx.sh                                                                  
---------------- start ----------------
failed to get from fields: resource temporarily unavailable{
 "height": "886",
 "txhash": "3A3489EBB8DB01406665AA184F79E479BBC8B3EA92D351CCDF5C21357B019704",
 "log": "Msg 0: ",
 "gas_wanted": "200000",
 "gas_used": "23926",
 "tags": [
  {
   "key": "action",
   "value": "buy_name"
  }
 ]
}
----------------  end  ----------------
➜  sdk-application-tutorial git:(master) ✗ cat batch-tx.sh 
#!/usr/bin/env bash

password=11111111

echo "---------------- start ----------------"
echo "11111111" | nscli tx nameservice buy-name alice.id1 10mycoin  --from alice &
echo "11111111" | nscli tx nameservice buy-name jack.id1 10mycoin  --from jack &
wait
echo "----------------  end  ----------------"
➜  sdk-application-tutorial git:(master) ✗ 
```

**Comment by yangyanqing** [comment]
The reason for the prompt `resource temporarily unavailable` is that LevelDB does not support multiple processes.

 Command `buy-name` would  query account info from `.nscli/keys/keys.db`, locked `.nscli/keys/keys.db/LOCK`. So, the second process could not get lock and exit with `resource temporarily unavailable`. Each command could release lock after 0.3 sec. The following script can execute successfully. 

```bash
➜  sdk-application-tutorial git:(master) ✗ cat batch-tx.sh 
#!/usr/bin/env bash

password=11111111
no=8

echo "---------------- start ----------------"
echo "${password}" | nscli tx nameservice buy-name alice.id${no} 10mycoin  --from alice &
sleep 0.3
echo "${password}" | nscli tx nameservice buy-name jack.id${no} 10mycoin  --from jack &
wait
echo "----------------  end  ----------------"
➜  sdk-application-tutorial git:(master) ✗
```

I think this issue could be closed. @jackzampolin @SorawitSiri
