### ISSUE TITLE
Account not found error when sending coins

### ISSUE THREAD

**Issue by SorawitSiri** [cosmos/sdk-application-tutorial#32]
How to create new account without restarting node for this tutorial?

**Comment by jackzampolin** [comment]
@SorawitSiri By running `gaiacli keys add {{ name }}`. What issue are you running into?

**Comment by SorawitSiri** [comment]
I initialize configuration and a genesis.json file for my application and an account for the transactions, start by running (nsd start) and i added account (nscli keys add jack) while node running. After that i sent transection to new account , it show error saying **account not found. It shouldn't get to the stage.** 

Are you suggest me?

**Comment by yangyanqing** [comment]
There are two ways to let account be found in chain:
1. Use `nsd add-genesis-account` to distribute some coin to the account.
2. Use `nscli tx send` to send some coin to the account.

Which way did your choose? @SorawitSiri

**Comment by SorawitSiri** [comment]
I'm sorry for the delayed reply. I was busy finding multiple solutions and debugging my own code.

Currently I found a trick to create account online using `auth.AccountKeeper` and adding it to the KVStore directly (I don't know if this is the correct method, but it works). 

I am closing this issue. 
Thank you all for the support

**Comment by ProgramCpp** [comment]
@SorawitSiri i used the account keeper to create accounts. But i still get error.

```
acc := k.accountKeeper.NewAccountWithAddress(ctx, addr)
k.accountKeeper.SetAccount(ctx, acc)
```

addr is what i got by,
```
abcdd keys add user2
```
but when i try to sign with the new account, i get the below error
```
abcdd tx abcd do-something param1  --from user1 --trace
Error: rpc error: code = NotFound desc = rpc error: code = NotFound desc = account <addr> not found: key not found
```
