### ISSUE TITLE
ERROR: broadcast_tx_commit

### ISSUE THREAD

**Issue by SorawitSiri** [cosmos/sdk-application-tutorial#34]
This below image(Client): ERROR: broadcast_tx_commit: Response error: RPC error -32603
![screen shot 2562-02-06 at 21 23 47](https://user-images.githubusercontent.com/34050939/52347929-b47a2000-2a55-11e9-944c-54baaa3e2c14.png)

This below image(Server): Error on broadcastTxCommit  
![screen shot 2562-02-06 at 21 23 42](https://user-images.githubusercontent.com/34050939/52347984-d1aeee80-2a55-11e9-85d4-889c04d37377.png)

Do you have any suggestions?

**Comment by jackzampolin** [comment]
@SorawitSiri It looks like you have significantly modified the tutorial code. A couple of thoughts:

- Images of logs don't allow for the level of inspection required to debug issues like this
- The level of customization implied here means this isn't the right place for this issue.
- We would need much more detail on the underlying code to find the issue.
- I think your best bet here is to ask this question with [more detail included on our forum](https://forum.cosmos.network/)
