### ISSUE TITLE
REST Server goes down after running for a while

### ISSUE THREAD

**Issue by SorawitSiri** [cosmos/sdk-application-tutorial#38]
This is below command which using run REST Server.
`mtcli rest-server --laddr tcp://0.0.0.0:1317 --trust-node`

**Comment by jackzampolin** [comment]
@SorawitSiri When you open an issue, please add some more details. There is no way to reproduce this issue or figure out what went wrong for you with the logs. Also it appears that you have made significant changes to the tutorial so I would also need a link to that code. I'm going to close this issue.
