### ISSUE TITLE
too many arguments in call to bcrypt

### ISSUE THREAD

**Issue by glints** [cosmos/sdk-application-tutorial#77]
I get the following when I'm trying to build the app:

make install
GO111MODULE=on go install -tags " ledger" ./cmd/nsd
# github.com/cosmos/cosmos-sdk/crypto/keys/mintkey
../../go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.34.2/crypto/keys/mintkey/mintkey.go:109:41: too many arguments in call to bcrypt.GenerateFromPassword
	have ([]byte, []byte, int)
	want ([]byte, int)
../../go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.34.2/crypto/keys/mintkey/mintkey.go:143:41: too many arguments in call to bcrypt.GenerateFromPassword
	have ([]byte, []byte, int)
	want ([]byte, int)
# github.com/cosmos/cosmos-sdk/crypto
../../go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.34.2/crypto/ledger_real.go:17:3: cannot use device (type *ledger_cosmos_go.LedgerCosmos) as type LedgerSECP256K1 in return argument:
	*ledger_cosmos_go.LedgerCosmos does not implement LedgerSECP256K1 (missing ShowAddressSECP256K1 method)
make: *** [install] Error 2

If I'm leaving out the ledger import I get a similar error.

**Comment by yangyanqing** [comment]
No error occurred on my MAC.

```bash
➜  sdk-application-tutorial git:(master) go version
go version go1.12 darwin/amd64
➜  sdk-application-tutorial git:(master) uname -a
Darwin yangyanqingdeMacBook-Pro.local 18.5.0 Darwin Kernel Version 18.5.0: Mon Mar 11 20:40:32 PDT 2019; root:xnu-4903.251.3~3/RELEASE_X86_64 x86_64
➜  sdk-application-tutorial git:(master) make install
GO111MODULE=on go install -tags " ledger" ./cmd/nsd
GO111MODULE=on go install -tags " ledger" ./cmd/nscli
➜  sdk-application-tutorial git:(master) 
```

**Comment by glints** [comment]
clone works.
In my own version it gives the error. Must be an error in my dependencies.
Thx for quick reply
