### ISSUE TITLE
Proposal: Add lite client routes

### ISSUE THREAD

**Issue by cwgoes** [cosmos/sdk-application-tutorial#8]
Most applications built on the SDK (and certainly a nameservice) will want lite client RPC functionality, I think we should demonstrate a minimum viable example of what that looks like.

Might block on https://github.com/cosmos/cosmos-sdk/issues/1081.

**Comment by alexanderbez** [comment]
Yes!!!

**Comment by jackzampolin** [comment]
Definatly! This _is_ blocked on https://github.com/cosmos/cosmos-sdk/issues/1081

**Comment by jackzampolin** [comment]
So this is no longer blocked, and I've done about 1/2 the work here (the code side). We still need a series of HTTP calls to show users how to call the routes (maybe in a `tutorial/run-rest.md`).
