### ISSUE TITLE
Examples of REST Server no longer working

### ISSUE THREAD

**Issue by patrickwieth** [cosmos/sdk-application-tutorial#80]
The examples given here: https://github.com/cosmos/sdk-application-tutorial/blob/master/tutorial/run-rest.md

no longer work. If one adjusts the curl commands as posted here: 
https://github.com/cosmos/sdk-application-tutorial/issues/76

then the results are unsigned jsons and no working buy-name is broadcasted. It would be nice to adjust the run-rest.md so that a working example is given.

**Comment by jackzampolin** [comment]
@patrickwieth thanks for the catch! Would you mind pushing a PR correct this?

**Comment by patrickwieth** [comment]
I don't know exactly how you intend to have this example. You have changed quite a lot here. Before it was done with https and the password was sent to the server and the server signed the message. Now you get an unsigned tx from the REST server and have to sign it with nscli tx sign and then you have to broadcast it. This is the way I got it working, but I don't know if you intend it to be like that? 
Especially broadcasting with nscli tx broadcast does not really make sense, there should be a REST endpoint for that right? So if you clarify how the intended usage is, I can write the readme, but currently how I got it working does not seem optimal.

**Comment by jackzampolin** [comment]
@patrickwieth due to security concerns about having the `gaiacli rest-server` managing keys we removed that functionality and haven't updated the example here.

**Comment by bobio2018** [comment]
> @patrickwieth due to security concerns about having the `gaiacli rest-server` managing keys we removed that functionality and haven't updated the example here.
> 
> The new flow requires a singer on the client (secure key management FTW) which might be hard to show in a concise example. Maybe just show transaction generation?

@jackzampolin I had the same issue for buying via REST, could you please update the tutorial with latest example of how to use a singer?

**Comment by patrickwieth** [comment]
my PR fixes this

**Comment by marbar3778** [comment]
Will close issue, since PR regarding this issue, has been merged
