### ISSUE TITLE
Validator set is nil in genesis and still empty after InitChain

### ISSUE THREAD

**Issue by ohJohanZ** [cosmos/sdk-application-tutorial#96]
`> nsd start`
I[2019-06-11|15:15:31.803] Starting ABCI with Tendermint                module=main
ERROR: Error during handshake: Error on replay: Validator set is nil in genesis and still empty after InitChain

**Comment by alexanderbez** [comment]
@ohJohanZ what version (commit hash) are you running?

**Comment by ohJohanZ** [comment]
> @ohJohanZ what version (commit hash) are you running?

commit 1c28fd2bd25ca21077ec2534f5a73e4ade9f503f (HEAD -> master, origin/master, origin/HEAD)

**Comment by marbar3778** [comment]
@ohJohanZ are you still encountering this problem?

**Comment by ohJohanZ** [comment]
@marbar3778 Yes, I still don't know how to solve it.

**Comment by marbar3778** [comment]
can you pull master again, then delete ~/.nsd & ~/.nscli files and start again, please let me know if the error persists, I am unable to duplicate the issue

**Comment by zhjgit** [comment]
I also encountered such a mistake, how can I solve it?

**Comment by fiowind** [comment]
> can you pull master again, then delete ~/.nsd & ~/.nscli files and start again, please let me know if the error persists, I am unable to duplicate the issue

I have encountered too
delete ~/.nsd & ~/.nscli files and start again, and this does work for me

**Comment by zouxyan** [comment]
Still have it ! Any help ？

**Comment by marbar3778** [comment]
Did you `nsd collect-gentxs`? Odd that this issue is still present.

**Comment by zouxyan** [comment]
I find that CN documentation is out of date. 
No ERROR following tutorials in EN.
